### ISSUE TITLE
Some images are truncated / not fully loaded

### ISSUE THREAD

**Issue by Twibit** [readium/SDKLauncher-Android#22] opened 2014-06-17 15:58 UTC
Hello,

It happens that some images in an epub are not fully loaded and not displayed correctly.
I saw it multiple times and not always on the same image/epub. 

Here is an example : 
![Screenshot](http://files.twibit.com/file/image/2B/export.jpeg)

**Comment by danielweck** [comment] 2015-01-07 17:31
Can this issue be reproduced with the latest code?

**Comment by danielweck** [comment] 2015-01-21 16:53
This is fixed in:
https://github.com/readium/SDKLauncher-Android/tree/feature/epubServerAndroidAsync
(not able to reproduce any media loading issues)

**Comment by danielweck** [comment] 2015-11-19 10:18
Was fixed in #50

**Closed by danielweck** 2015-11-19 10:18 UTC
Labels: Android, bug, priority high [critical]
