### ISSUE TITLE
Gradle build Error with NDK 14.0.3529234 rc1

### ISSUE THREAD

**Issue by PittyXu** [readium/SDKLauncher-Android#110] opened 2017-01-06 08:48 UTC
I clone the project, and run `./gradlew build`  with NDK 14.0.3529234 rc1.
Got the error.

``` shell
./gradlew build
app: Use gradle experimental to build application
Build Js Assets
1483692278093
6 Jan 2017 08:44:38 GMT
epub3: Use gradle experimental to build application
Build includes
Incremental java compilation is an incubating feature.
:epub3:copyEpub3XmlIncludes UP-TO-DATE
:epub3:copyEpub3UtilitiesIncludes UP-TO-DATE
:epub3:copyEpub3RootIncludes UP-TO-DATE
:epub3:copyEpub3Includes UP-TO-DATE
:epub3:copyGoogleUrlBaseIncludes UP-TO-DATE
:epub3:copyGoogleUrlIncludes UP-TO-DATE
:epub3:copyLibxmlIncludes UP-TO-DATE
:epub3:copyLibzipBaseIncludes UP-TO-DATE
:epub3:copySha1Includes UP-TO-DATE
:epub3:copyUtf8Includes UP-TO-DATE
:epub3:buildIncludes UP-TO-DATE
:epub3:buildMk
Android NDK: WARNING:ndk-bundle/sources/cxx-stl/gnu-libstdc++/Android.mk:epub3: LOCAL_LDLIBS is always ignored for static libraries    
Android NDK: WARNING:ndk-bundle/sources/cxx-stl/gnu-libstdc++/Android.mk:epub3: LOCAL_LDLIBS is always ignored for static libraries    
make: Entering directory `SDKLauncher-Android/readium-sdk/Platform/Android/epub3'
[armeabi-v7a] Compile++ thumb: epub3 <= sha1.cpp
In file included from ././../../../ePub3/ThirdParty/sha1/sha1.cpp:16:
././../../../ePub3/ThirdParty/sha1/sha1.h:29:23: error: extra qualification on member 'lrot'
                static Uint32 SHA1::lrot( Uint32 x, int bits );
                              ~~~~~~^
././../../../ePub3/ThirdParty/sha1/sha1.h:30:21: error: extra qualification on member 'storeBigEndianUint32'
                static void SHA1::storeBigEndianUint32( unsigned char* byte, Uint32 num );
                            ~~~~~~^
././../../../ePub3/ThirdParty/sha1/sha1.h:31:21: error: extra qualification on member 'hexPrinter'
                static void SHA1::hexPrinter( unsigned char* c, int l );
                            ~~~~~~^
3 errors generated.
make: *** [SDKLauncher-Android/readium-sdk/Platform/Android/epub3/obj/local/armeabi-v7a/objs/epub3/./__/__/__/ePub3/ThirdParty/sha1/sha1.o] Error 1
make: Leaving directory `SDKLauncher-Android/readium-sdk/Platform/Android/epub3'
:epub3:buildMk FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':epub3:buildMk'.
> Process 'command 'ndk-bundle/ndk-build'' finished with non-zero exit value 2
```

**Comment by PittyXu** [comment] 2017-01-06 08:54
Fix the error by edit sha1.h 28~29 line to
```cpp
// utility methods
static Uint32 lrot( Uint32 x, int bits );
static void storeBigEndianUint32( unsigned char* byte, Uint32 num );
static void hexPrinter( unsigned char* c, int l );
```

But got error
```shell
:epub3:buildMk
Executing task ':epub3:buildMk' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Starting process 'command 'ndk-bundle/ndk-build''. Working directory: SDKLauncher-Android/readium-sdk/Platform/Android/epub3 Command: ndk-bundle/ndk-build -C SDKLauncher-Android/readium-sdk/Platform/Android/epub3 NDK_APPLICATION_MK=Application.mk APP_BUILD_SCRIPT=Experimental.mk NDK_PROJECT_PATH=SDKLauncher-Android/readium-sdk/Platform/Android/epub3
Successfully started process 'command 'ndk-bundle/ndk-build''
Android NDK: WARNING:ndk-bundle/sources/cxx-stl/gnu-libstdc++/Android.mk:epub3: LOCAL_LDLIBS is always ignored for static libraries    
Android NDK: WARNING:ndk-bundle/sources/cxx-stl/gnu-libstdc++/Android.mk:epub3: LOCAL_LDLIBS is always ignored for static libraries    
make: Entering directory `SDKLauncher-Android/readium-sdk/Platform/Android/epub3'
[armeabi-v7a] Compile thumb  : epub3 <= zip_add.c
In file included from ././../../../ePub3/ThirdParty/libzip/zip_add.c:36:
In file included from ././../../../ePub3/ThirdParty/libzip/zipint.h:39:
In file included from ././../../../ePub3/ThirdParty/libzip/zip.h:37:
In file included from ./include/ePub3/_config.h:72:
./include/ePub3/_platform.h:189:11: fatal error: 'backup_atomics.h' file not found
# include <backup_atomics.h>
          ^
1 error generated.
make: make: Leaving directory `SDKLauncher-Android/readium-sdk/Platform/Android/epub3'
*** [SDKLauncher-Android/readium-sdk/Platform/Android/epub3/obj/local/armeabi-v7a/objs/epub3/./__/__/__/ePub3/ThirdParty/libzip/zip_add.o] Error 1
:epub3:buildMk FAILED
:epub3:buildMk (Thread[Daemon worker Thread 8,5,main]) completed. Took 0.363 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':epub3:buildMk'.
> Process 'command ndk-bundle/ndk-build'' finished with non-zero exit value 2
```

**Comment by danielweck** [comment] 2017-01-06 09:12
Could you please test with the latest stable release NDK r13b?
https://developer.android.com/ndk/downloads/index.html

There are significant changes in the compiler toolchain (especially with regards to Clang  / GCC deprecation).

**Comment by danielweck** [comment] 2017-05-22 11:36
I am not able to reproduce build errors on the `develop` or `feature/lcp` branches, with Gradle "stable" or "experimental", in DEBUG or RELEASE mode, in ARMv7 or x86 modes.
So, I am closing this issue.
Feel free to re-open when more information is available.
Thanks!

**Closed by danielweck** 2017-05-22 11:36 UTC
Labels: func:Builds, platform:Android, priority:Medium, type:Question
